/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package foodcourt;

import java.awt.Color;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.Iterator;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.xssf.usermodel.XSSFRow;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

/**
 *
 * @author Regawa
 */
public class Table extends javax.swing.JFrame {

    /**
     * Creates new form Table
     */
    public Table() {
        initComponents();
        try {
            // TODO add your handling code here:
            tampilDataMeja();
        } catch (Exception ex) {
            System.out.println(ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        pTable1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pTable2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        pTable3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        pTable4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        pTable5 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        pTable6 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        pTable7 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        pTable8 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        pTable9 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        pTable10 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        pTable11 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        pTable12 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        pTable13 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        pTable14 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        pTable15 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        pTable16 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        pTable17 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        pTable18 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        pTable19 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        pTable20 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        background = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(255, 58, 10));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setFocusable(false);
        jPanel1.setPreferredSize(new java.awt.Dimension(200, 150));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 161, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 96, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(93, 335, 161, 96));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setFocusable(false);
        jPanel4.setPreferredSize(new java.awt.Dimension(200, 150));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 161, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 96, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(93, 475, 161, 96));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setFocusable(false);
        jPanel5.setPreferredSize(new java.awt.Dimension(200, 150));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 161, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 96, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(93, 208, 161, 96));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setFocusable(false);
        jPanel6.setPreferredSize(new java.awt.Dimension(200, 150));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 161, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 96, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(93, 615, 161, 96));

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setFocusable(false);
        jPanel8.setPreferredSize(new java.awt.Dimension(200, 150));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 161, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 96, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1094, 335, 161, 96));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setFocusable(false);
        jPanel7.setPreferredSize(new java.awt.Dimension(200, 150));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 161, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 96, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1094, 208, 161, 96));

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setFocusable(false);
        jPanel10.setPreferredSize(new java.awt.Dimension(200, 150));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 161, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 96, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1094, 615, 161, 96));

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setFocusable(false);
        jPanel9.setPreferredSize(new java.awt.Dimension(200, 150));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 161, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 96, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1094, 475, 161, 96));

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));
        jPanel11.setFocusable(false);
        jPanel11.setPreferredSize(new java.awt.Dimension(200, 150));

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 161, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 96, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(297, 56, 161, 96));

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));
        jPanel12.setFocusable(false);
        jPanel12.setPreferredSize(new java.awt.Dimension(200, 150));

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 161, Short.MAX_VALUE)
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 96, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(499, 56, 161, 96));

        jPanel13.setBackground(new java.awt.Color(255, 255, 255));
        jPanel13.setFocusable(false);
        jPanel13.setPreferredSize(new java.awt.Dimension(200, 150));

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 161, Short.MAX_VALUE)
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 96, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(694, 56, 161, 96));

        jPanel14.setBackground(new java.awt.Color(255, 255, 255));
        jPanel14.setFocusable(false);
        jPanel14.setPreferredSize(new java.awt.Dimension(200, 150));

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 161, Short.MAX_VALUE)
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 96, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(899, 56, 161, 96));

        pTable1.setBackground(new java.awt.Color(118, 255, 3));

        jLabel1.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel1.setText("1");

        javax.swing.GroupLayout pTable1Layout = new javax.swing.GroupLayout(pTable1);
        pTable1.setLayout(pTable1Layout);
        pTable1Layout.setHorizontalGroup(
            pTable1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pTable1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addContainerGap(30, Short.MAX_VALUE))
        );
        pTable1Layout.setVerticalGroup(
            pTable1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pTable1Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        getContentPane().add(pTable1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 240, 60, 60));

        pTable2.setBackground(new java.awt.Color(0, 204, 0));

        jLabel4.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel4.setText("2");

        javax.swing.GroupLayout pTable2Layout = new javax.swing.GroupLayout(pTable2);
        pTable2.setLayout(pTable2Layout);
        pTable2Layout.setHorizontalGroup(
            pTable2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pTable2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel4)
                .addContainerGap(29, Short.MAX_VALUE))
        );
        pTable2Layout.setVerticalGroup(
            pTable2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pTable2Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addContainerGap())
        );

        getContentPane().add(pTable2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 240, -1, -1));

        pTable3.setBackground(new java.awt.Color(0, 204, 0));

        jLabel5.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel5.setText("3");

        javax.swing.GroupLayout pTable3Layout = new javax.swing.GroupLayout(pTable3);
        pTable3.setLayout(pTable3Layout);
        pTable3Layout.setHorizontalGroup(
            pTable3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pTable3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel5)
                .addContainerGap(27, Short.MAX_VALUE))
        );
        pTable3Layout.setVerticalGroup(
            pTable3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pTable3Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addContainerGap())
        );

        getContentPane().add(pTable3, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 240, -1, -1));

        pTable4.setBackground(new java.awt.Color(0, 204, 0));

        jLabel6.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel6.setText("4");

        javax.swing.GroupLayout pTable4Layout = new javax.swing.GroupLayout(pTable4);
        pTable4.setLayout(pTable4Layout);
        pTable4Layout.setHorizontalGroup(
            pTable4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pTable4Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel6)
                .addContainerGap(26, Short.MAX_VALUE))
        );
        pTable4Layout.setVerticalGroup(
            pTable4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pTable4Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addContainerGap())
        );

        getContentPane().add(pTable4, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 240, -1, -1));

        pTable5.setBackground(new java.awt.Color(0, 204, 0));

        jLabel7.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel7.setText("5");

        javax.swing.GroupLayout pTable5Layout = new javax.swing.GroupLayout(pTable5);
        pTable5.setLayout(pTable5Layout);
        pTable5Layout.setHorizontalGroup(
            pTable5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pTable5Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel7)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        pTable5Layout.setVerticalGroup(
            pTable5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pTable5Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addContainerGap())
        );

        getContentPane().add(pTable5, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 240, -1, -1));

        pTable6.setBackground(new java.awt.Color(0, 204, 0));

        jLabel22.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel22.setText("6");

        javax.swing.GroupLayout pTable6Layout = new javax.swing.GroupLayout(pTable6);
        pTable6.setLayout(pTable6Layout);
        pTable6Layout.setHorizontalGroup(
            pTable6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pTable6Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel22)
                .addContainerGap(26, Short.MAX_VALUE))
        );
        pTable6Layout.setVerticalGroup(
            pTable6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pTable6Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(jLabel22)
                .addContainerGap())
        );

        getContentPane().add(pTable6, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 380, 60, 60));

        pTable7.setBackground(new java.awt.Color(0, 204, 0));

        jLabel17.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel17.setText("7");

        javax.swing.GroupLayout pTable7Layout = new javax.swing.GroupLayout(pTable7);
        pTable7.setLayout(pTable7Layout);
        pTable7Layout.setHorizontalGroup(
            pTable7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pTable7Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel17)
                .addContainerGap(27, Short.MAX_VALUE))
        );
        pTable7Layout.setVerticalGroup(
            pTable7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pTable7Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(jLabel17)
                .addContainerGap())
        );

        getContentPane().add(pTable7, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 380, -1, -1));

        pTable8.setBackground(new java.awt.Color(0, 204, 0));

        jLabel14.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel14.setText("8");

        javax.swing.GroupLayout pTable8Layout = new javax.swing.GroupLayout(pTable8);
        pTable8.setLayout(pTable8Layout);
        pTable8Layout.setHorizontalGroup(
            pTable8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pTable8Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel14)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        pTable8Layout.setVerticalGroup(
            pTable8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pTable8Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(jLabel14)
                .addContainerGap())
        );

        getContentPane().add(pTable8, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 380, -1, -1));

        pTable9.setBackground(new java.awt.Color(0, 204, 0));

        jLabel13.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel13.setText("9");

        javax.swing.GroupLayout pTable9Layout = new javax.swing.GroupLayout(pTable9);
        pTable9.setLayout(pTable9Layout);
        pTable9Layout.setHorizontalGroup(
            pTable9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pTable9Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel13)
                .addContainerGap(26, Short.MAX_VALUE))
        );
        pTable9Layout.setVerticalGroup(
            pTable9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pTable9Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addContainerGap())
        );

        getContentPane().add(pTable9, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 380, -1, -1));

        pTable10.setBackground(new java.awt.Color(0, 204, 0));

        jLabel8.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel8.setText("10");

        javax.swing.GroupLayout pTable10Layout = new javax.swing.GroupLayout(pTable10);
        pTable10.setLayout(pTable10Layout);
        pTable10Layout.setHorizontalGroup(
            pTable10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pTable10Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel8)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        pTable10Layout.setVerticalGroup(
            pTable10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pTable10Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addContainerGap())
        );

        getContentPane().add(pTable10, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 380, -1, -1));

        pTable11.setBackground(new java.awt.Color(0, 204, 0));

        jLabel21.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel21.setText("11");

        javax.swing.GroupLayout pTable11Layout = new javax.swing.GroupLayout(pTable11);
        pTable11.setLayout(pTable11Layout);
        pTable11Layout.setHorizontalGroup(
            pTable11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pTable11Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel21)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        pTable11Layout.setVerticalGroup(
            pTable11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pTable11Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(jLabel21)
                .addContainerGap())
        );

        getContentPane().add(pTable11, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 500, 60, 60));

        pTable12.setBackground(new java.awt.Color(0, 204, 0));

        jLabel18.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel18.setText("12");

        javax.swing.GroupLayout pTable12Layout = new javax.swing.GroupLayout(pTable12);
        pTable12.setLayout(pTable12Layout);
        pTable12Layout.setHorizontalGroup(
            pTable12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pTable12Layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(jLabel18)
                .addGap(23, 23, 23))
        );
        pTable12Layout.setVerticalGroup(
            pTable12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pTable12Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(jLabel18)
                .addContainerGap())
        );

        getContentPane().add(pTable12, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 500, -1, -1));

        pTable13.setBackground(new java.awt.Color(0, 204, 0));

        jLabel15.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel15.setText("13");

        javax.swing.GroupLayout pTable13Layout = new javax.swing.GroupLayout(pTable13);
        pTable13.setLayout(pTable13Layout);
        pTable13Layout.setHorizontalGroup(
            pTable13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pTable13Layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(jLabel15)
                .addGap(24, 24, 24))
        );
        pTable13Layout.setVerticalGroup(
            pTable13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pTable13Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(jLabel15)
                .addContainerGap())
        );

        getContentPane().add(pTable13, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 500, -1, -1));

        pTable14.setBackground(new java.awt.Color(0, 204, 0));

        jLabel12.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel12.setText("14");

        javax.swing.GroupLayout pTable14Layout = new javax.swing.GroupLayout(pTable14);
        pTable14.setLayout(pTable14Layout);
        pTable14Layout.setHorizontalGroup(
            pTable14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pTable14Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel12)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        pTable14Layout.setVerticalGroup(
            pTable14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pTable14Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addContainerGap())
        );

        getContentPane().add(pTable14, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 500, -1, -1));

        pTable15.setBackground(new java.awt.Color(0, 204, 0));

        jLabel9.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel9.setText("15");

        javax.swing.GroupLayout pTable15Layout = new javax.swing.GroupLayout(pTable15);
        pTable15.setLayout(pTable15Layout);
        pTable15Layout.setHorizontalGroup(
            pTable15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pTable15Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel9)
                .addContainerGap(27, Short.MAX_VALUE))
        );
        pTable15Layout.setVerticalGroup(
            pTable15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pTable15Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addContainerGap())
        );

        getContentPane().add(pTable15, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 500, -1, -1));

        pTable16.setBackground(new java.awt.Color(0, 204, 0));

        jLabel20.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel20.setText("16");

        javax.swing.GroupLayout pTable16Layout = new javax.swing.GroupLayout(pTable16);
        pTable16.setLayout(pTable16Layout);
        pTable16Layout.setHorizontalGroup(
            pTable16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pTable16Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel20)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        pTable16Layout.setVerticalGroup(
            pTable16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pTable16Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(jLabel20)
                .addContainerGap())
        );

        getContentPane().add(pTable16, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 620, 60, 60));

        pTable17.setBackground(new java.awt.Color(0, 204, 0));

        jLabel19.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel19.setText("17");

        javax.swing.GroupLayout pTable17Layout = new javax.swing.GroupLayout(pTable17);
        pTable17.setLayout(pTable17Layout);
        pTable17Layout.setHorizontalGroup(
            pTable17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pTable17Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel19)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        pTable17Layout.setVerticalGroup(
            pTable17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pTable17Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(jLabel19)
                .addContainerGap())
        );

        getContentPane().add(pTable17, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 620, -1, -1));

        pTable18.setBackground(new java.awt.Color(0, 204, 0));

        jLabel16.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel16.setText("18");

        javax.swing.GroupLayout pTable18Layout = new javax.swing.GroupLayout(pTable18);
        pTable18.setLayout(pTable18Layout);
        pTable18Layout.setHorizontalGroup(
            pTable18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pTable18Layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(jLabel16)
                .addGap(24, 24, 24))
        );
        pTable18Layout.setVerticalGroup(
            pTable18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pTable18Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(jLabel16)
                .addContainerGap())
        );

        getContentPane().add(pTable18, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 620, -1, -1));

        pTable19.setBackground(new java.awt.Color(0, 204, 0));

        jLabel11.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel11.setText("19");

        javax.swing.GroupLayout pTable19Layout = new javax.swing.GroupLayout(pTable19);
        pTable19.setLayout(pTable19Layout);
        pTable19Layout.setHorizontalGroup(
            pTable19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pTable19Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel11)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        pTable19Layout.setVerticalGroup(
            pTable19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pTable19Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addContainerGap())
        );

        getContentPane().add(pTable19, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 620, -1, -1));

        pTable20.setBackground(new java.awt.Color(0, 204, 0));

        jLabel10.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel10.setText("20");

        javax.swing.GroupLayout pTable20Layout = new javax.swing.GroupLayout(pTable20);
        pTable20.setLayout(pTable20Layout);
        pTable20Layout.setHorizontalGroup(
            pTable20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pTable20Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel10)
                .addContainerGap(26, Short.MAX_VALUE))
        );
        pTable20Layout.setVerticalGroup(
            pTable20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pTable20Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addContainerGap())
        );

        getContentPane().add(pTable20, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 620, -1, -1));

        background.setBackground(new java.awt.Color(26, 26, 26));
        background.setPreferredSize(new java.awt.Dimension(1366, 768));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(8, 117, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 39, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 39, Short.MAX_VALUE)
        );

        background.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, -1, -1));

        jPanel3.setBackground(new java.awt.Color(133, 0, 0));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 39, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 39, Short.MAX_VALUE)
        );

        background.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("occupied");
        background.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("unoccupied");
        background.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, -1, -1));

        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Table().setVisible(true);
            }
        });
    }

    void tampilDataMeja() throws FileNotFoundException, IOException {
        final String FILE_MEJA = "src/data/dataMeja.xlsx";
        final String MEJA_MERAH="#850000";
        final String MEJA_HIJAU="#087300";
        FileInputStream fis = new FileInputStream(new File(FILE_MEJA));

        XSSFWorkbook workbook;
        workbook = new XSSFWorkbook(fis);
        XSSFSheet spreadsheet = workbook.getSheetAt(0);
        Iterator<Row> rowIterator = spreadsheet.iterator();
        XSSFRow row;
        while (rowIterator.hasNext()) {
            row = (XSSFRow) rowIterator.next();
            int noMeja = Integer.parseInt(String.valueOf(Math.round(row.getCell(0).getNumericCellValue())));
            int status = Integer.parseInt(String.valueOf(Math.round(row.getCell(1).getNumericCellValue())));
            Color tableColor;
            if (status == 0) {
                tableColor = Color.decode(MEJA_HIJAU);
            } else {
                tableColor = Color.decode(MEJA_MERAH);
            }
            switch (noMeja) {
                case 1:
                    pTable1.setBackground(tableColor);
                    break;
                case 2:
                    pTable2.setBackground(tableColor);
                    break;
                case 3:
                    pTable3.setBackground(tableColor);
                    break;
                case 4:
                    pTable4.setBackground(tableColor);
                    break;
                case 5:
                    pTable5.setBackground(tableColor);
                    break;
                case 6:
                    pTable6.setBackground(tableColor);
                    break;
                case 7:
                    pTable7.setBackground(tableColor);
                    break;
                case 8:
                    pTable8.setBackground(tableColor);
                    break;
                case 9:
                    pTable9.setBackground(tableColor);
                    break;
                case 10:
                    pTable10.setBackground(tableColor);
                    break;
                case 11:
                    pTable11.setBackground(tableColor);
                    break;
                case 12:
                    pTable12.setBackground(tableColor);
                    break;
                case 13:
                    pTable13.setBackground(tableColor);
                    break;
                case 14:
                    pTable14.setBackground(tableColor);
                    break;
                case 15:
                    pTable15.setBackground(tableColor);
                    break;
                case 16:
                    pTable16.setBackground(tableColor);
                    break;
                case 17:
                    pTable17.setBackground(tableColor);
                    break;
                case 18:
                    pTable18.setBackground(tableColor);
                    break;
                case 19:
                    pTable19.setBackground(tableColor);
                    break;
                case 20:
                    pTable20.setBackground(tableColor);
                    break;
            }
            System.out.println("hehe");
        }
        fis.close();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel pTable1;
    private javax.swing.JPanel pTable10;
    private javax.swing.JPanel pTable11;
    private javax.swing.JPanel pTable12;
    private javax.swing.JPanel pTable13;
    private javax.swing.JPanel pTable14;
    private javax.swing.JPanel pTable15;
    private javax.swing.JPanel pTable16;
    private javax.swing.JPanel pTable17;
    private javax.swing.JPanel pTable18;
    private javax.swing.JPanel pTable19;
    private javax.swing.JPanel pTable2;
    private javax.swing.JPanel pTable20;
    private javax.swing.JPanel pTable3;
    private javax.swing.JPanel pTable4;
    private javax.swing.JPanel pTable5;
    private javax.swing.JPanel pTable6;
    private javax.swing.JPanel pTable7;
    private javax.swing.JPanel pTable8;
    private javax.swing.JPanel pTable9;
    // End of variables declaration//GEN-END:variables
}
